# Generated by Django 5.0.6 on 2024-07-02 16:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('reviews', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Publisher',
        ),
    ]
