# Generated by Django 5.0.6 on 2024-07-02 16:21

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('reviews', '0002_delete_publisher'),
    ]

    operations = [
        migrations.CreateModel(
            name='Publisher',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='The name of the publisher', max_length=50)),
                ('website', models.URLField(help_text="The Publisher's Website")),
                ('email', models.EmailField(help_text='The Publisher"s email address.', max_length=254)),
            ],
        ),
    ]
